### ISSUE TITLE
Erroneously detects data being piped to stdin

### ISSUE THREAD

**Issue by luckman212** [boyter/hashit#3]
First off: awesome project! This is _insanely_ faster 🚀  than [`rhash`](https://github.com/rhash/RHash) on my Mac M1.

I tried using it as a drop-in replacement in some shell scripts, and ran into an issue where it was always hashing `stdin` instead of the filename arg I was passing.

e.g.
```shell
while (( $# > 0 )); do
  ~/go/bin/hashit --hash sha256 --format json -- "$1" | jq -r '.[] | .SHA256'
  shift
done
```
was always printing the same hash regardless of whatever file(s) I passed to the script. I had to add `</dev/null` to make it cooperate. 
```shell
while (( $# > 0 )); do
  ~/go/bin/hashit </dev/null --hash sha256 --format json -- "$1" | jq -r '.[] | .SHA256'
  shift
done
```
Not sure how to fix this the "right" way.

**Comment by boyter** [comment]
Thanks for the kind words!

Now that's an interesting one. I am not sure about this either come to think of it. My shell skills are pretty weaksauce though. My understanding is that is looping though files, and passing them into hashit which is then picking it up as stdin, but you are actually specifying the file?

Please let me know if that's correct? If so that is erroneous behavior, but im not sure I am reading it correctly.

**Comment by luckman212** [comment]
Thanks for the reply, I should have given a more specific example. You're correct, the snippet above is meant to be saved as a script and passed some args in the form of filenames.

If you add a shebang to the above codeblock and then try passing 3 files to it, hopefully you'll be able to reproduce the bug. 

save as **hashit-test.sh**:
```bash
#!/usr/bin/env bash

while (( $# > 0 )); do
  ~/go/bin/hashit --hash sha256 --format json -- "$1" | jq -r '.[] | .SHA256'
  shift
done
```

then
```bash
chmod u+x hashit-test.sh
./hashit-test.sh file1 file2 file3
```

All that being said, I skimmed the Go code and it looks like you "did it right" so I wish I could be more helpful on that front.

**Comment by boyter** [comment]
If this is a case of just wanting the following output

```
$ ./hashit-test.sh main.go                  
04a8f7bf05a58fcbf2581b699f4271a6956d938bd330bc6a400722a2ef4fa5fc
```

Where you want the hash on a newline, I could implement that for you instead? Saves you having to `jq` it and I could see that being useful in shell scripts.

**Comment by luckman212** [comment]
Sure, it definitely would be nice to have a `--format hashonly` option.

But, the stdin bug isn't related to piping to `jq`, so that change alone wouldn't really solve this problem.

**Comment by boyter** [comment]
> But, the stdin bug isn't related to piping to jq, so that change alone wouldn't really solve this problem.

Yep, just thought I could improve your life a little bit there at the same time.

**Comment by boyter** [comment]
Added `hashonly` into master if you feel like building from master.

As for the other issue this actually is a bug! When a file and stdin was added, both were being processed. I missed this through my integration tests! I have fixed the tests and set it now only process the stdin IF it detects stdin AND no files/directories are supplied.

I have pushed both fixes into master if you feel like building from there to resolve it. Otherwise if you could confirm its working in your case I will push a new release.

You should be able to update your script to the following now

```
#!/usr/bin/env bash

while (( $# > 0 )); do
  ~/go/bin/hashit --hash sha256 --format hashonly
  shift
done
```

And hopefully it should work as you expect.

**Comment by luckman212** [comment]
Wonderful! I built from master and just tested. Confirming that the bug is fixed, and the `--format hashonly` option is working great as well. I really appreciate your work on this!

**Comment by boyter** [comment]
Excellent. Going to push out a new release then. Thanks for being so prompt in confirming the fix.

**Comment by boyter** [comment]
Done new release pushed.
